/**
 * Navigation - Builds and manages the sidebar navigation tree
 * Skill → Topic → Article hierarchy with expand/collapse
 *
 * Note: innerHTML is used safely here as all content comes from the local
 * manifest.json file which is generated by the build script from local files.
 * No untrusted user input is rendered.
 */

class Navigation {
    constructor(containerSelector) {
        this.container = document.querySelector(containerSelector);
        this.manifest = null;
        this.onArticleSelect = null;
    }

    /**
     * Load the manifest and build the navigation tree
     */
    async init() {
        try {
            const response = await fetch('content/manifest.json');
            this.manifest = await response.json();
            this.render();
            this.updateActiveState();
        } catch (error) {
            console.error('Failed to load manifest:', error);
            this.renderError();
        }
    }

    /**
     * Escape HTML to prevent XSS (defense in depth)
     */
    escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    /**
     * Render the navigation tree
     */
    render() {
        if (!this.manifest || !this.manifest.skills) {
            this.renderEmpty();
            return;
        }

        // Clear container
        this.container.textContent = '';

        const ul = document.createElement('ul');
        ul.className = 'nav-skill';

        this.manifest.skills.forEach(skill => {
            ul.appendChild(this.renderSkill(skill));
        });

        this.container.appendChild(ul);
        this.attachEventListeners();
    }

    /**
     * Create an SVG element
     */
    createIcon(type) {
        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('viewBox', '0 0 24 24');
        svg.setAttribute('fill', 'none');
        svg.setAttribute('stroke', 'currentColor');
        svg.setAttribute('stroke-width', '2');

        const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');

        if (type === 'folder') {
            svg.classList.add('nav-icon');
            path.setAttribute('d', 'M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z');
            svg.appendChild(path);
        } else if (type === 'chevron') {
            svg.classList.add('nav-chevron');
            const polyline = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
            polyline.setAttribute('points', '9 18 15 12 9 6');
            svg.appendChild(polyline);
        } else if (type === 'file') {
            svg.classList.add('nav-icon');
            const path1 = document.createElementNS('http://www.w3.org/2000/svg', 'path');
            path1.setAttribute('d', 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z');
            const polyline = document.createElementNS('http://www.w3.org/2000/svg', 'polyline');
            polyline.setAttribute('points', '14 2 14 8 20 8');
            const line1 = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line1.setAttribute('x1', '16'); line1.setAttribute('y1', '13');
            line1.setAttribute('x2', '8'); line1.setAttribute('y2', '13');
            const line2 = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line2.setAttribute('x1', '16'); line2.setAttribute('y1', '17');
            line2.setAttribute('x2', '8'); line2.setAttribute('y2', '17');
            svg.appendChild(path1);
            svg.appendChild(polyline);
            svg.appendChild(line1);
            svg.appendChild(line2);
        }

        return svg;
    }

    /**
     * Render a skill (top-level folder)
     */
    renderSkill(skill) {
        const isExpanded = router.shouldExpandSkill(skill.slug);

        const li = document.createElement('li');
        li.className = 'nav-item' + (isExpanded ? ' expanded' : '');
        li.dataset.skill = skill.slug;

        const header = document.createElement('div');
        header.className = 'nav-item-header';
        header.dataset.type = 'skill';
        header.dataset.skill = skill.slug;

        header.appendChild(this.createIcon('folder'));

        const label = document.createElement('span');
        label.className = 'nav-label';
        label.textContent = skill.name;
        header.appendChild(label);

        header.appendChild(this.createIcon('chevron'));

        li.appendChild(header);

        const childrenUl = document.createElement('ul');
        childrenUl.className = 'nav-children nav-topic';

        skill.topics.forEach(topic => {
            childrenUl.appendChild(this.renderTopic(skill, topic));
        });

        li.appendChild(childrenUl);

        return li;
    }

    /**
     * Render a topic (second-level folder)
     */
    renderTopic(skill, topic) {
        const isExpanded = router.shouldExpandTopic(skill.slug, topic.slug);

        const li = document.createElement('li');
        li.className = 'nav-item' + (isExpanded ? ' expanded' : '');
        li.dataset.skill = skill.slug;
        li.dataset.topic = topic.slug;

        const header = document.createElement('div');
        header.className = 'nav-item-header';
        header.dataset.type = 'topic';
        header.dataset.skill = skill.slug;
        header.dataset.topic = topic.slug;

        header.appendChild(this.createIcon('folder'));

        const label = document.createElement('span');
        label.className = 'nav-label';
        label.textContent = topic.name;
        header.appendChild(label);

        header.appendChild(this.createIcon('chevron'));

        li.appendChild(header);

        const childrenUl = document.createElement('ul');
        childrenUl.className = 'nav-children nav-article';

        topic.articles.forEach(article => {
            childrenUl.appendChild(this.renderArticle(skill, topic, article));
        });

        li.appendChild(childrenUl);

        return li;
    }

    /**
     * Render an article (leaf node)
     */
    renderArticle(skill, topic, article) {
        const isActive = router.isActive(skill.slug, topic.slug, article.slug);
        const path = router.buildPath(skill.slug, topic.slug, article.slug);

        const li = document.createElement('li');
        li.className = 'nav-item';
        li.dataset.skill = skill.slug;
        li.dataset.topic = topic.slug;
        li.dataset.article = article.slug;

        const link = document.createElement('a');
        link.className = 'nav-item-header' + (isActive ? ' active' : '');
        link.href = '#' + path;
        link.dataset.type = 'article';

        link.appendChild(this.createIcon('file'));

        const label = document.createElement('span');
        label.className = 'nav-label';
        label.textContent = article.title;
        link.appendChild(label);

        li.appendChild(link);

        return li;
    }

    /**
     * Attach event listeners to navigation items
     */
    attachEventListeners() {
        // Skill and Topic headers (toggle expand/collapse)
        this.container.querySelectorAll('.nav-item-header[data-type="skill"], .nav-item-header[data-type="topic"]').forEach(header => {
            header.addEventListener('click', (e) => {
                e.preventDefault();
                const navItem = header.closest('.nav-item');
                navItem.classList.toggle('expanded');
            });
        });
    }

    /**
     * Update active state based on current route
     */
    updateActiveState() {
        // Remove all active classes
        this.container.querySelectorAll('.nav-item-header.active').forEach(el => {
            el.classList.remove('active');
        });

        // Collapse all
        this.container.querySelectorAll('.nav-item.expanded').forEach(el => {
            el.classList.remove('expanded');
        });

        const route = router.parseHash();
        if (!route.skill) return;

        // Expand and highlight based on route
        const skillItem = this.container.querySelector(`[data-skill="${route.skill}"]`);
        if (skillItem) {
            skillItem.classList.add('expanded');
        }

        if (route.topic) {
            const topicItem = this.container.querySelector(`[data-skill="${route.skill}"][data-topic="${route.topic}"]`);
            if (topicItem) {
                topicItem.classList.add('expanded');
            }
        }

        if (route.article) {
            const articleLink = this.container.querySelector(
                `[data-skill="${route.skill}"][data-topic="${route.topic}"][data-article="${route.article}"] .nav-item-header`
            );
            if (articleLink) {
                articleLink.classList.add('active');
            }
        }
    }

    /**
     * Get all articles for search
     */
    getAllArticles() {
        const articles = [];
        if (!this.manifest || !this.manifest.skills) return articles;

        this.manifest.skills.forEach(skill => {
            skill.topics.forEach(topic => {
                topic.articles.forEach(article => {
                    articles.push({
                        title: article.title,
                        slug: article.slug,
                        skill: skill.name,
                        skillSlug: skill.slug,
                        skillFolder: skill.folder,
                        topic: topic.name,
                        topicSlug: topic.slug,
                        topicFolder: topic.folder,
                        file: article.file,
                        path: `content/${skill.folder}/${topic.folder}/${article.file}.md`
                    });
                });
            });
        });

        return articles;
    }

    /**
     * Get article path by slugs
     */
    getArticlePath(skillSlug, topicSlug, articleSlug) {
        if (!this.manifest || !this.manifest.skills) return null;

        const skill = this.manifest.skills.find(s => s.slug === skillSlug);
        if (!skill) return null;

        const topic = skill.topics.find(t => t.slug === topicSlug);
        if (!topic) return null;

        const article = topic.articles.find(a => a.slug === articleSlug);
        if (!article) return null;

        return `content/${skill.folder}/${topic.folder}/${article.file}.md`;
    }

    /**
     * Render empty state
     */
    renderEmpty() {
        this.container.textContent = '';

        const div = document.createElement('div');
        div.className = 'empty-state';

        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('viewBox', '0 0 24 24');
        svg.setAttribute('fill', 'none');
        svg.setAttribute('stroke', 'currentColor');
        svg.setAttribute('stroke-width', '2');
        const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
        path.setAttribute('d', 'M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z');
        svg.appendChild(path);
        div.appendChild(svg);

        const p = document.createElement('p');
        p.textContent = 'No content yet. Add skills and articles to get started.';
        div.appendChild(p);

        this.container.appendChild(div);
    }

    /**
     * Render error state
     */
    renderError() {
        this.container.textContent = '';

        const div = document.createElement('div');
        div.className = 'empty-state';

        const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
        svg.setAttribute('viewBox', '0 0 24 24');
        svg.setAttribute('fill', 'none');
        svg.setAttribute('stroke', 'currentColor');
        svg.setAttribute('stroke-width', '2');
        const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        circle.setAttribute('cx', '12');
        circle.setAttribute('cy', '12');
        circle.setAttribute('r', '10');
        const line1 = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        line1.setAttribute('x1', '12'); line1.setAttribute('y1', '8');
        line1.setAttribute('x2', '12'); line1.setAttribute('y2', '12');
        const line2 = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        line2.setAttribute('x1', '12'); line2.setAttribute('y1', '16');
        line2.setAttribute('x2', '12.01'); line2.setAttribute('y2', '16');
        svg.appendChild(circle);
        svg.appendChild(line1);
        svg.appendChild(line2);
        div.appendChild(svg);

        const p = document.createElement('p');
        p.textContent = 'Failed to load navigation. Check if manifest.json exists.';
        div.appendChild(p);

        this.container.appendChild(div);
    }
}
